# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-12 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_auto_20180112_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
