# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_auto_20180112_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('1', 'enabled'), ('0', 'disabled')], default='0', max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('date_last_change', models.DateField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255, verbose_name='Пароль устройства')),
                ('wan', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('lan', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.RenameField(
            model_name='externalnumber',
            old_name='calling_line',
            new_name='AON',
        ),
        migrations.RenameField(
            model_name='internalnumber',
            old_name='inner_number_passwd',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='internalnumber',
            name='access_to_MG',
        ),
        migrations.RemoveField(
            model_name='internalnumber',
            name='calling_line_id',
        ),
        migrations.RemoveField(
            model_name='internalnumber',
            name='inner_number',
        ),
        migrations.RemoveField(
            model_name='internalnumber',
            name='lan',
        ),
        migrations.RemoveField(
            model_name='internalnumber',
            name='login_device',
        ),
        migrations.RemoveField(
            model_name='internalnumber',
            name='pass_device',
        ),
        migrations.RemoveField(
            model_name='internalnumber',
            name='wan',
        ),
        migrations.AddField(
            model_name='internalnumber',
            name='number',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalnumber',
            name='type',
            field=models.CharField(choices=[('SKD', 'СКД'), ('MTT', 'МТТ'), ('MOA', 'МОА')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='externalnumber',
            name='type_of_access',
            field=models.CharField(choices=[('any', 'общий'), ('specific', 'выделенный'), ('free', 'свободный')], max_length=10),
        ),
        migrations.AlterField(
            model_name='internalnumber',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone.Device'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='customer',
            name='ExternalNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone.ExternalNumber'),
        ),
        migrations.AddField(
            model_name='customer',
            name='InternalNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone.InternalNumber'),
        ),
    ]
