# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0006_auto_20180119_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ExternalNumber',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='InternalNumber',
        ),
        migrations.RemoveField(
            model_name='internalnumber',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='internalnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone.InternalNumber'),
        ),
        migrations.AddField(
            model_name='externalnumber',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone.Customer'),
        ),
        migrations.AddField(
            model_name='internalnumber',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone.Customer'),
        ),
    ]
