# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0007_auto_20180122_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='internalnumber',
        ),
        migrations.AddField(
            model_name='internalnumber',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone.Device'),
        ),
        migrations.AlterField(
            model_name='internalnumber',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone.Customer'),
        ),
    ]
