# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-24 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0010_auto_20180124_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalnumber',
            name='AON',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='internalnumber',
            name='number',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
