# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-24 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0011_auto_20180124_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_type', models.CharField(choices=[('SKD', 'СКД'), ('MTT', 'МТТ'), ('MOA', 'МОА')], default='MTT', max_length=20)),
                ('internal_number', models.CharField(max_length=6, unique=True)),
                ('internal_password', models.CharField(max_length=20)),
                ('AON', models.CharField(max_length=11)),
                ('type_of_access', models.CharField(choices=[('any', 'общий'), ('specific', 'выделенный'), ('free', 'свободный')], max_length=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone.Customer')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone.Device')),
            ],
        ),
        migrations.RemoveField(
            model_name='externalnumber',
            name='internalnumber',
        ),
        migrations.RemoveField(
            model_name='internalnumber',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='internalnumber',
            name='device',
        ),
        migrations.DeleteModel(
            name='ExternalNumber',
        ),
        migrations.DeleteModel(
            name='InternalNumber',
        ),
    ]
