# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-24 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0012_auto_20180124_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('1', 'Активный'), ('0', 'Отключен')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='number',
            name='AON',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='number',
            name='internal_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='number',
            name='type_of_access',
            field=models.CharField(choices=[('any', 'общий'), ('specific', 'выделенный'), ('free', 'свободный')], default='free', max_length=10),
        ),
    ]
