# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-12 12:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0014_auto_20180126_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='AON',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_external_number', message='must be AMTEL number', regex='^8(4951089[567]\\d{2}|49598304[0-2]\\d|49598305[2-4]\\d|4959830550)$')]),
        ),
        migrations.AlterField(
            model_name='number',
            name='internal_number',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_internal_number', message='must be = 6 digits', regex='^\\d{6}$')]),
        ),
    ]
